---
title: "Homework 3 solutions"
author: "Zichen Shu"
output: github_document

---

```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)

theme_set(theme_minimal() + theme(legend.position = "botton"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_color_viridis_d
```

## Problem 1

Read in the data.

```{r, message = FALSE}
homicide_df = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```

Look at this a bit

```{r, message = FALSE}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total))  %>% 
    broom::tidy()

```

Try to iterate ......

```{r}
results_df = aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~ prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```

```{r, include = FALSE}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

  results_df %>% 
  arrange(estimate) %>%
  mutate(city_state = fct_inorder(city_state)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

```

## Problem 2

```{r, message = FALSE}
path_df = 
  tibble(path = list.files("lda_data"),) %>% 
  mutate(path = str_c("lda_data/", path),
         map_df(path, read_csv)
    ) %>% 
  separate(path, into = c("lda", "subject_id"), sep = "/") %>% 
  separate(subject_id, into = c("subject_id", "csv"), sep = "\\.") %>% 
  select(-lda, -csv) %>% 
  pivot_longer(week_1:week_8, 
               names_to = "week",
               values_to = "value")
```


```{r}
path_df %>% 
  group_by(subject_id) %>% 
  summarize(
    mean = mean(value)
  ) %>% 
  knitr::kable()
  
  
path_df %>% 
  ggplot(aes(x = week, y = value, group = subject_id, color = subject_id))+
  geom_line(alpha = 0.5)+
  theme(legend.position = "right")
```

## Problem 3

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```



















